### ISSUE TITLE
Creating vpn_pihole error

### ISSUE THREAD

**Issue by kennethhaspeel** [mr-bolle/docker-openvpn-pihole#11]
When i try your script everything runs fine until vpn_pihole needs to be created

I'm getting
`ERROR: for vpn_pihole  Cannot start service pihole: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/timezone\\\" to rootfs \\\"/var/lib/docker/overlay2/db5bcd01a6f78bfe2da8c1cd32a47d4f4ace333f0432e0f6ced9349d888edfd9/merged\\\" at \\\"/var/lib/docker/overlay2/db5bcd01a6f78bfe2da8c1cd32a47d4f4ace333f0432e0f6ced9349d888edfd9/merged/etc/timezone\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

~~Second thing. I cannot find the created key. I looked in /etc/openvpn but there's nothing. It would seem openvpn is up and running.~~
That was an major stupid moment from me

**Comment by mr-bolle** [comment]
Hi, what Host-OS you use? I change the source of the TimeZone from Volumes, to the [Environment](https://github.com/pi-hole/docker-pi-hole#environment-variables). 
`     environment:
       TZ: 'Europa/Berlin'`

If you change docker-compose, you can run the container with `docker-compose up -d`

**docker-compose.yml**
```
`version: '3'
# https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md

services:
   openvpn:
     cap_add:
       - NET_ADMIN
     container_name: vpn_openvpn
     image: kylemanna/openvpn
     ports:
       - "1194:1194/udp"
       - "1194:1194/tcp"
     environment:
      #  - VIRTUAL_PORT=${VIRTUAL_PORT_OPENVPN}
      #  - VIRTUAL_HOST=${VIRTUAL_HOST_OPENVPN}
      #  - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_VPN}
      #  - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      #  - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      #  - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      #  - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      #  - LOCAL_NETWORK=192.168.0.0/24
       OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60 -–log-driver json-file --log-opt max-size=10m
     volumes:
#      - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
       - ./openvpn_data:/etc/openvpn
     restart: always
     networks:
       vpn-net:
         ipv4_address: 172.110.1.3
     logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "3"

   pihole:
     image: pihole/pihole
     container_name: vpn_pihole
     cap_add:
       - NET_ADMIN     
     dns:
       - 127.0.0.1
       - 1.1.1.1
     depends_on:
       - openvpn
     ports:
       #- "553:53/tcp"
       #- "553:53/udp"
       - "8081:80/tcp"
     environment:
       TZ: 'Europa/Berlin'
	   WEBPASSWORD: fcvFjLIO2hWhkFCi
# #1 Digitalcourage | #2 Chaos Computer Club
       DNS1: 46.182.19.48
       DNS2: 213.73.91.35
     volumes:
       - ./pihole:/etc/pihole
       - ./pihole/dnsmasq.d:/etc/dnsmasq.d
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
     restart: always
     networks:
       vpn-net:
         ipv4_address: 172.110.1.4     
     logging:
       driver: "json-file"
       options:
         max-size: "5m"
         max-file: "3"

# docker network create --driver=bridge --subnet=172.110.1.0/24 --gateway=172.110.1.1 vpn-net
networks:
  vpn-net:
    external: true

```

**Comment by kennethhaspeel** [comment]
I'm using a pretty fresh install of Ubuntu 18.04.
I'll test this later this week.
I was guessing it had something to do with timezone (pretty obvious) but i lack the knowledge to solve it. Thank you

**Comment by mr-bolle** [comment]
Using the command line, you can use sudo dpkg-reconfigure tzdata.

* Open a terminal window by going to Applications>Accessories>Terminal.
* `sudo dpkg-reconfigure tzdata`  
* Follow the directions in the terminal.
The timezone info is saved in `cat /etc/timezone` - which can be edited or used below.

**Comment by mr-bolle** [comment]
please reopen again, if you have still this issue
