### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Shaun-Harrison** [mr-bolle/docker-openvpn-pihole#13]
Above error while running 

bash openvpn-install.sh 

On raspberry pi3 on Step 3 after entering a Client Name

**Comment by mr-bolle** [comment]
Hi, 

it is strange that you get this error on step 3, it seams like you have the issue with the creating of the OpenVPN Image for your ARM CPU.

Could you run this script to create a image again, with a other alpine version 3.8 https://github.com/mr-bolle/docker-openvpn-pihole/blob/dev/buildimage.sh

**Comment by Shaun-Harrison** [comment]
Hello @mr-bolle 

Sorry for the delay!

So what I done was changed the openvpn-install.sh part of the script to look like this

    # Upgrade Alpine Image for OpenVPN
      IMAGE_LINE=`cat -n $DOCKERFILE_CUSTOM | grep FROM |  awk '{print $1}'`       # search line with the old Image
      sed -i ${IMAGE_LINE}d $DOCKERFILE_CUSTOM                                                        # delete this old Image
      sed -i "${IMAGE_LINE}a\FROM alpine:3.8" $DOCKERFILE_CUSTOM            # append new Image

Where FROM alpine was originally alpine:3.8.4 

Still no luck though, however I noticed that it was not step 3 that was the issue but step 4 - so the issue is with the following command 

    docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full $CLIENTNAME nopass

**Comment by mr-bolle** [comment]
Please use follow script, i have change the image from *alpine* to *arm32v6/alpine*
Unfornataly i don't have a RPi3 to test before.  If you have still some issues, please post the full openvon-install shell report.

```
git clone https://github.com/mr-bolle/docker-openvpn-pihole.git -b dev
cd docker-openvpn-pihole && bash openvpn-install-arm.sh
```

**Comment by mr-bolle** [comment]
Hi @Shaun-Harrison do you try to create the openvpn image, and can run this container?

**Comment by Shaun-Harrison** [comment]
Hello! Yes this now works on my RPI3 thank you!
