### ISSUE TITLE
What should be edited to work with my use case ? 

### ISSUE THREAD

**Issue by kevincaradant** [mr-bolle/docker-openvpn-pihole#15]
Hi @mr-bolle ,

I want to use OpenVpn and PiHole together but I'm nooby with all of these stuff, it's new for me :)
Hopping, you can help me a little bit ;)

I currently have an OpenVpn docker with port-share enabled with the IP(172.24.X.X) of the OpenVPN docker (my configuration):

```
version: '3'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn:latest
    container_name: openvpn
    ports:
      - "443:1194/tcp"
    restart: unless-stopped
    environment:
      - PORT-SHARE=172.24.X.X 444
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
```

After that, I have in my nginx (virtual-hosts) with a listen on 444 to redirect on my azerty.mydomain.com, azerty2.mydomain.com ect

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name azerty.mydomain.com;
        return 301 https://$server_name$request_uri;
}

server {
    listen 444 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    root /media/toto/storage;
    autoindex on;
    server_name azerty.mydomain.com;
    location / {
      try_files $uri $uri/ =404;
      auth_basic "Restricted Content";
      auth_basic_user_file /etc/nginx/.htpasswd1;
    }

}
```

My clients (phone / computer) are directly connected in 443 which is the behavior that I want. 

What is the most simple thing I can do to keep this behavior like that ? 
Do you see something more easy ? I want to keep the 443 port because 1194 is sometimes blocked in airport for example ;)

If you can explain to me with some words what I have to change / what is the best idea or simply with a docker-compose.yml updated if it's more simple and quick for you ;)

Thanks

Regards

**Comment by mr-bolle** [comment]
Hi,

this was also my idea, unfornatally i don't had time to try this setup with a differend OpenVPN Port. As far as i see, do you already read this [tcp documetation](https://github.com/kylemanna/docker-openvpn/blob/master/docs/tcp.md) from kylemanna. I would adjust the enviroment port-share and replace the container IP to your domain.

 ```
environment: 
- port-share=azerty.mydomain.com 444
```

If you would change your VPN-Network Subnet, you have to change the docker-compose.yml 
```     
networks:
       vpn-net:
         ipv4_address: 172.110.1.XXX
```
And have to change into your *openvpn_data/openvpn.conf* the dhcp-option DNS to your new Pi-Hole Container IP
```
### Push Configurations Below
push "block-outside-dns"
push "dhcp-option DNS 172.110.1.4"       << Container IP from Pi-Hole

```

**Comment by kevincaradant** [comment]
Hi :)

> As far as i see, do you already read this tcp documetation from kylemanna

I'm not sure if it was a question or not, but yes I already read it ;)

>I would adjust the enviroment port-share and replace the container IP to your domain.

Alright but why specify one address instead of my docker IP of VPN ? I have 8 different address (azerty.domain.com,azerty2.domain.com,azerty3.domain.com ect). I choose one of them without thinking to somewhat ? That will be my external IP if I choose for example azerty.mydomain.com

> networks:
>       vpn-net:
>         ipv4_address: 172.110.1.XXX"

 You mean I have to add this, in the docker-compose of openvpn or pi-hole or both ? 
What is 172.110.1.XXX, is it the internal ip of my server ? ip of openvpn docker ? ip of pi-hole docker ? Something else ? 

> push "dhcp-option DNS 172.110.1.4"       << Container IP from Pi-Hole

I understood this part :P 

Sorry if it's seems to be simple and logical for you, I try but don't worry, your help is very useful :) 

EDIT: I tried with azerty.mydomain.com but port-share failed to reach the URL. Only the IP of OpenVPN container works as exected. What's wrong from my side ?

**Comment by kevincaradant** [comment]
To complete my answer. The main problem is the port already used.
Indeed, OpenVpn container uses the 443 port that PiHole container wants to use. So I can't start PiHole if OpenVpn is already running. 
Thanks ')

**Comment by mr-bolle** [comment]
@kevincaradant do you want to access to the pi-hole web interface over the external network? If not (for my point of view it is not necessary) you have to map the port 80 to example 8081 (host port)

```
ports: 
#- "553:53/tcp" 
#- "553:53/udp" 
- "8081:80/tcp"
```

Otherwise you have to set the environment **VIRTUAL_HOST** [Link](https://github.com/pi-hole/docker-pi-hole/blob/master/README.md#environment-variables) and for that you have to create a virtual host on your nginx proxy.

**Comment by kevincaradant** [comment]
No I don't want to access to the pi-hole web interface over the external network.

However, I read from some topics, that it was good to let 80 and 443 port on the Pi-Hole container.

From the official documentation:
```
Port 443 is to provide a sinkhole for ads that use SSL. If only port 80 is used, then blocked HTTPS queries will fail to connect to port 443 and may cause long loading times. 
```

So I'm not sure if Pi-hole will works as expected if I change the port 80 by 8081 for example and completely remove 443 port from the dokcer-compose for Pi-Hole :/

And sorry to be focus on that, but could you please answer me about my questions here. Thank you :D https://github.com/mr-bolle/docker-openvpn-pihole/issues/15#issuecomment-578435933

**Comment by mr-bolle** [comment]
> Alright but why specify one address instead of my docker IP of VPN ? I have 8 different address (azerty.domain.com,azerty2.domain.com,azerty3.domain.com ect). I choose one of them without thinking to somewhat ? That will be my external IP if I choose for example azerty.mydomain.com

Why you want to use 8 domain for one container, the reverse proxy should be able to handle the traffic. I use the static container IP setting, that docker don't change the IP if you restart your container.

> You mean I have to add this, in the docker-compose of openvpn or pi-hole or both ?
What is 172.110.1.XXX, is it the internal ip of my server ? ip of openvpn docker ? ip of pi-hole docker ? Something else ?

Both, if you change your sub-network you have to change the IP from both Container (into the same sub-network range)  into my docker-compose i use 172.110.1.3 for OpenVPN and 172.110.1.4 for Pi-Hole.

hopefully now it is more clear.

**Comment by kevincaradant** [comment]
> Why you want to use 8 domain for one container, the reverse proxy should be able to handle the traffic

Because I have 8 different websites (available from the external networks) which are linked to different Docker containers via Nginx as reverse proxy like (emby , home assistant ect ect). You seem to be disturbed by that ? :)
For the moment I don't have domain for Openvpn container (why should I get one ? I don't want to access to it. For the clients, I use one of my 8 sub domains with 443 port). 
Also not for pi-hole (available by local ip only in internal) so no need sub domain for that I guess

> Both, if you change your sub-network you have to change the IP from both Container (into the same sub-network range) into my docker-compose i use 172.110.1.3 for OpenVPN and 172.110.1.4 for Pi-Hole.

Ok so I should have something like that for pi-hole ? (without the # of course)
![image](https://user-images.githubusercontent.com/6093175/73211328-55248c80-414c-11ea-82ae-f822cbff998c.png)
(for the moment I can't let the 443 port here... until I find a solution ^^)

And this one for Openvpn container ? 
![image](https://user-images.githubusercontent.com/6093175/73211442-88ffb200-414c-11ea-8f15-d63e76976124.png)
Or Should I have to create the network again in this docker-compose ? 

> hopefully now it is more clear.

Yes almost perfect :D
Hoping it's the last time I ask you questions to avoid to bother you anymore. I know I ask you a lot of things, thank you to have taken the time for it :)

**Comment by mr-bolle** [comment]
> Because I have 8 different websites (available from the external networks) which are linked to different Docker containers via Nginx as reverse proxy like (emby , home assistant ect ect). You seem to be disturbed by that ? :)

there is no need to create one connection for every service what you have. This setup use one VPN connection with the pi-hole to block unwanted domains. If you are connected to your local network, you have access to all your services.

 **note** please put both services (openvpn and pi-hole) in one docker-compose.yml - there should be work together, with different compose files it is more difficult.

And replace the port-share to a external domain, and set this domain during your openvpn setup.

**Comment by kevincaradant** [comment]
Thanks a lot :)

I completly forgot your repo during all my fails tries, and when I spoke with you :/
With your docker-compose.yml config ... very useful to help me to understand the network configuration. 

I understood also that I have to change your file to match with mine and then, I can execute your .sh to setup everything ... 
I'm dumb sometimes, I ask to you  some questions for nothing sorry  ;)

However, for the port-share, I got an error until I wrote 172.110.1.1 ! which my gateway IP...
And I'm not sure that everything which is on my NAS, is analyzed by PiHole...
For example, it's not the real URL but if it was  https://pouet.mydomain.com. 
From external I can go on it but PiHole doesn't see nothing :/

![image](https://user-images.githubusercontent.com/6093175/73221080-4942c580-4160-11ea-9595-aebc4218c7e8.png)

![image](https://user-images.githubusercontent.com/6093175/73221112-5b246880-4160-11ea-8380-0ac07f4e2f81.png)

EDIT: From my phone with VPN that seems to be better :)
![image](https://user-images.githubusercontent.com/6093175/73222268-1ea63c00-4163-11ea-9be2-dbb8d8399db9.png)
But I thought it should works even without using VPN :/. Any idea how to do that for some specifics URL ? Like my domains opens on external ?

cf from your shell script
```
# create a new sub-network (if not exist)
docker network inspect vpn-net &>/dev/null || 
    docker network create --driver=bridge --subnet=172.110.1.0/24 --gateway=172.110.1.1 vpn-net
```
 
port-share corresponding to your gateway and it's the only IP which work ;)
So I don't understand why I can't put any of my sub domains here
I saw it using `ifconfig | grep 172.110`

EDIT: Maybe, it's related to DHCP server. I should disable the router DHCP and enable it from PiHole. I will try tomorrow to see that.
If it's that, it's not related to docker from this project or whatever :)

**Comment by mr-bolle** [comment]
>  And I'm not sure that everything which is on my NAS, is analyzed by PiHole...
> EDIT: From my phone with VPN that seems to be better :)

This Setup use Pihole if you use your OpenVPN Connection (thats why i open only the Pihole Port 8081:80) 
If you would handle your local Network Access with Pihole, you have to create a other Pihole instance. (Example below)
And with your docker-openvpn-pihole compose you remove the Port-Mapping from Pi-Hole 53/tcp,53/udp ,67/udp)

> EDIT: Maybe, it's related to DHCP server. I should disable the router DHCP and enable it from PiHole. I will try tomorrow to see that.  

please try this setup first with the DHCP Server from your Router, and do this changes later if everythink works.


example: docker-compose-pihole.yml  

```
version: '3'
# https://raw.githubusercontent.com/quidsup/notrack/master/malicious-sites.txt
# https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt
# https://v.firebog.net/hosts/static/SamsungSmart.txt

services:
  pihole:
     image: pihole/pihole
     container_name: pihole_lokal
     cap_add:
       - NET_ADMIN
     ports:
       - "53:53/tcp"
       - "53:53/udp"
       - "800:80/tcp"
     dns:
       - 127.0.0.1
       - 1.1.1.1
     environment:
       - WEBPASSWORD=MoreSecurePassword
       - PROXY_LOCATION=pihole.lokal
# #1 Digitalcourage | #2 Chaos Computer Club
       - DNS1=46.182.19.48
       - DNS2=213.73.91.35
     volumes:
       - ./pihole/pihole:/etc/pihole
       - ./pihole/dnsmasq.d:/etc/dnsmasq.d
#       - ./pihole/overwrite_resolv.conf:/etc/resolv.conf
       - /etc/timezone:/etc/timezone:ro
     restart: unless-stopped
```

**Comment by kevincaradant** [comment]
> And with your docker-openvpn-pihole compose you remove the Port-Mapping from Pi-Hole 53/tcp,53/udp ,67/udp)

Ok so I'm not sure to understand. If I follow your previous example named "pihole-local", you let the mapping 53 in the ports. But you removed 67.
What should have I between the local docker and the openvpn docker ? 

For the moment I have:
docker-openvpn-pihole => 53 (udp/tcp) 67 (udp) and 8081(GUI)
docker-pihole-local => 800(GUI)

And that seems to not working (nothing is blocked by local pihole)

Edit: I tried the opposite, as you can see it :
![image](https://user-images.githubusercontent.com/6093175/73306912-730df200-421d-11ea-9791-0baefe36fd0f.png)

And same behavior :/

**Comment by mr-bolle** [comment]
> But you removed 67.
What should have I between the local docker and the openvpn docker ?

Until now i don't need (i don't use pi-hole DHCP Server, i change the DNS Server into my router), you can add this port on your local instance. 

> And that seems to not working (nothing is blocked by local pihole)

Do you have changed the DNS Server from any client, if you run your pihole-local? 

If yes, you have to disconnect your client, or use the command prompt from your windows client `ipconfig /flushdns` than you should see some blocking domain. 

**You have to use the IP from your server (ex. 192.168.178.25) not the container IP.**

**Comment by kevincaradant** [comment]
OK I see, I will check tonight, I'm not sure about what I have done or not yesterday. Not sure my router (gave by default during registration to have Internet) allow to do that by the way ... Maybe I should buy an other router :/

If its not good, I have to change manually on my computer to test it with the local ip of the server which have PiHole in 192.168.1.X. Is it exact? :) 

I read somewhere, if you change the dns server from the router, you don't need change anything from clients on the same network in WiFi or ethernet. Is it what you did at your home? 

Info for me => The dns server for my clients is the local IP of my server (192.168.1.100) which host PiHole with Docker? 

And in the container, the dns settings in PiHole, are the dns of Google for example. Dns1 and dns2 specified in the docker in your previous answer yesterday. 

To test the PiHole (local), I don't need to create some special networks allowing to communicate with PiHole as external? I don't need to create anything ? 

I will check it tonight! Thanks :)

**Comment by mr-bolle** [comment]
> If its not good, I have to change manually on my computer to test it with the local ip of the server which have PiHole in 192.168.1.X. Is it exact? :)

Yes, for your test, you can change your DNS Server from your computer. But use the IP from your Server, then all DNS requests will use the Port 53 from your local pihole. If you don't change your DNS Server on your router / computer, all DNS requests will be sent so your default DNS Server (and you want pihole behind)

> Is it what you did at your home?

Yes, i want the whole internet traffic from all devices into my home network over pihole.

> Info for me => The dns server for my clients is the local IP of my server (192.168.1.100) which host PiHole with Docker?

Yes

> And in the container, the dns settings in PiHole, are the dns of Google for example. Dns1 and dns2 specified in the docker in your previous answer yesterday.

DNS1 and DNS2 into the pi-hole container is necessary, that pihole received the external IP from the not blocked domain. Otherwise you don't get a response from any domain.

> To test the PiHole (local), I don't need to create some special networks allowing to communicate with PiHole as external? I don't need to create anything ?

No, for the local pihole container, you don't need to set a other network. Docker create a new one by themselves.

I wish you a lot of success (Even if these explanations have nothing to do with this repository)

**Comment by mr-bolle** [comment]
Hi @kevincaradant do you have success with your setup?

**Comment by kevincaradant** [comment]
Hi :)
Not yet, since one week (my last message) I didn't have time to check it... I'm very busy in the moment, I had 4 huge tasks in the same time to do. However, I will try to do it this week, don't worry I will tell you when it I'll be good or not ^^.

I didn't answer to you m because I want to do it when I will use your answer to continue this setup ')

Edit 15/02: I bought a router. I will try ASAP to do a good setup :)

**Comment by kevincaradant** [comment]
Update: I didn't have time to answer here before today ;)
For the moment I have two different instances of Pi-Hole, one under OpenVpn and an other one under internal network with a specific DNS with my router.
With this setup, everything works well :)
