### ISSUE TITLE
cannot get openvpn and pihole containers working on Raspberry Pi 4 B+ . "Waiting for server response..." in Tunnelblick app

### ISSUE THREAD

**Issue by ross-shulyha** [mr-bolle/docker-openvpn-pihole#16]
Hello mr-bolle, I cannot get my openvpn and pihole containers working on Raspberry Pi 4 B+ using your script. When I'm adding a newly created ovpn client to my Tunneblick app on macOS it only displays a message "Waiting for server response..." without any further changes.

I did not modify any of the files and used exactly the same files from your repository except only one thing - I've changed the default openvpn udp port (in your docker-compose.yml it was - "1194:1194/udp"). I've double checked that the same port that I chose I'm using for port forwarding correctly.
Please point me into the right direction.

I have also a few questions:
1) For openvpn service and pihole service in docker-compose.yml you specified ipv4_address: 172.110.1.3 and ipv4_address: 172.110.1.4 respectively, should I adjust those IP address to fit my network local IP addresses (for example 192.168.1.3 , 192.168.1.4 ) ?
2) In what places do I need to specify my Raspberry Pi IP address ?
3) Should a dynDNS subdomain look only like **vpn**.<my_domain>.com or instead of a **vpn** subdomain name I can use my own subdomain name that I came up with? Should I specify a port in it as well ?

**Comment by ross-shulyha** [comment]
wow...I've struggled with that for 2 days in a row and figured it out. You should had place into the description that currently the only supported port is a default port of 1194.

**Comment by mr-bolle** [comment]
Sorry for this late reply, I would change the documentation soon. Thank you for feedback.

**Comment by mr-bolle** [comment]
done 
add [preparation](https://github.com/mr-bolle/docker-openvpn-pihole#10-preparation) section, feel free to improve this and create a pull request
