### ISSUE TITLE
OpenVPN throwing error on installation

### ISSUE THREAD

**Issue by diogomartino** [mr-bolle/docker-openvpn-pihole#17]
Hello. I'm using RPI 2B DietPI with Docker 19.03.8, and your installation script is throwing an error on Step 2.

> Performing Step 1, we are going to make a directory at /openvpn_data
> 
> ** OpenVPN Data Path is set to: /root/lmao/docker-openvpn-pihole/openvpn_data  *                                                 *
> 
> Please enter your dynDNS Address:
> Please choose your Protocol (tcp / [udp]):   udp
> Please enter the Pi-Hole Admin Password (default [fcvFjLIO2hWhkFCi]): asd
> 
> Step 2
> 
> Common name not specified, see '-u'
> usage: /usr/local/bin/ovpn_genconfig [-d]
>                   -u SERVER_PUBLIC_URL
>                  [-e EXTRA_SERVER_CONFIG ]
>                  [-E EXTRA_CLIENT_CONFIG ]
>                  [-f FRAGMENT ]
>                  [-n DNS_SERVER ...]
>                  [-p PUSH ...]
>                  [-r ROUTE ...]
>                  [-s SERVER_SUBNET]
> 
> optional arguments:
>  -2    Enable two factor authentication using Google Authenticator.
>  -a    Authenticate  packets with HMAC using the given message digest algorithm                                                  (auth).
>  -b    Disable 'push block-outside-dns'
>  -c    Enable client-to-client option
>  -C    A list of allowable TLS ciphers delimited by a colon (cipher).
>  -d    Disable default route
>  -D    Do not push dns servers
>  -k    Set keepalive. Default: '10 60'
>  -m    Set client MTU
>  -N    Configure NAT to access external server network
>  -t    Use TAP device (instead of TUN device)
>  -T    Encrypt packets with the given cipher algorithm instead of the default on                                                 e (tls-cipher).
>  -z    Enable comp-lzo compression.
> Cleaning up before Exit ...

If you are still maintaining this repo, fix it please. Thanks!

**Comment by bluetoothfx** [comment]
Hello, with Docker version 18.09.7, build 2d0083d it is working fine.

**Comment by mr-bolle** [comment]
Hi, 

could it be that you don't set the OpenVPN Domain?

> **Please enter your dynDNS Address:**
> Please choose your Protocol (tcp / [udp]): udp
> Please enter the Pi-Hole Admin Password (default [fcvFjLIO2hWhkFCi]): asd
> 
> Step 2
> 
> Common name not specified, see '-u'
> usage: /usr/local/bin/ovpn_genconfig [-d]
> -u SERVER_PUBLIC_URL

#### openvpn-install.sh details
<details>
<summary>from Step 1</summary>

```
Performing Step 1, we are going to make a directory at /openvpn_data

** OpenVPN Data Path is set to: /home/dietpi/docker_config/docker-openvpn-pihole/openvpn_data  **

Please enter your dynDNS Address:            test.domain.com
Please choose your Protocol (tcp / [udp]):   
Please enter the Pi-Hole Admin Password (default [fcvFjLIO2hWhkFCi]): piholePassword

Step 2

Processing PUSH Config: 'block-outside-dns'
Processing Route Config: '192.168.254.0/24'
Processing PUSH Config: 'dhcp-option DNS 172.110.1.4'
Processing PUSH Config: 'comp-lzo no'
Successfully generated config
Cleaning up before Exit ...

After a Shortwhile You need to enter your Server Secure Password details please wait ...


We are now at Step 3

```
</details>

**Comment by diogomartino** [comment]
I don't think I set that, as it is optional, I guess? In the meantime I configured my containers myself, but next time I need it I'm gonna try this again, as it is way faster to configure.

**Comment by mr-bolle** [comment]
If you have any suggestions, feel free to make a pull request or send any hints.
