### ISSUE TITLE
Easy-RSA error during installation

### ISSUE THREAD

**Issue by Dani-Pi** [mr-bolle/docker-openvpn-pihole#19]
Hello, big thank you for your work first!
I've installed Docker and Docker-Compose on my Raspberry Pi 4 with Raspbian as OS following the instructions on [https://withblue.ink/2019/07/13/yes-you-can-run-docker-on-raspbian.html](url)
Then I followed your instruction to get docker-openvpn-pihole installed. Everything worked fine until step 3. The following error message occured and the script was aborted:

*We are now at Step 3*
*Easy-RSA error:*
*The file '/etc/openvpn/vars' was not found.*

**Can you please support?**

**My software versions:**
docker-compose version 1.25.5, build unknown
docker-py version: 4.2.0
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019

**Comment by mr-bolle** [comment]
Hi, 

i create a new branch and a other Openvpn Image [mr-bolle/docker-openvpn-arm](https://github.com/mr-bolle/docker-openvpn-arm)

please try follow command 

:information_source: the reason for this problem could be an update from EasyRSA to 3.7.0 - and I have read that $OPENVPN/vars are no longer necessary https://bbs.archlinux.org/viewtopic.php?id=244380

```
git clone  https://github.com/mr-bolle/docker-openvpn-pihole.git -b rpi-dev && cd docker-openvpn-pihole && bash openvpn-install.sh

```

**Comment by mr-bolle** [comment]
@Dani-Pi could you give me a feedback if it works with you? I would like to publish this solution for all user

**Comment by Dani-Pi** [comment]
Hello @mr-bolle,
sorry for the late reply. I had some other issues with my Pi and no time to fix it...
I've installed the provided image on a fresh set up Raspberry Pi 4, built up with the latest NextCloudPi-Image (03-28-20). Everything worked fine till "Generating a RSA private key". I've entered pass phrase and after that script ended with Easy-RSA Error.


Generating a RSA private key
.......+++++
...................................................+++++
writing new private key to '/etc/openvpn/pki/private/nc.danielspi.de.key.XXXXeOpipA'
-----
Using configuration from /usr/share/easy-rsa/openssl-easyrsa.cnf
Enter pass phrase for /etc/openvpn/pki/private/ca.key:
unable to load CA private key
3069400272:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:563:
3069400272:error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:p12_decr.c:108:
3069400272:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:p12_decr.c:139:
3069400272:error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib:pem_pkey.c:142:

Easy-RSA error:

signing failed (openssl output above may have more detail)

**Comment by mr-bolle** [comment]
Your image have a firewall, for your openvpn client you have to allow the port 1194. You can also try pi-vpn and install before pi-hole. And during pi-vpn installation you set the customer dns to your host IP, than you have also a VPN connection with pi-hole.

Unfortunately i don't have time, to check how it works with this repository and your image.

**Comment by Dani-Pi** [comment]
Thank you for the hint. I will try to fix it.

**Comment by xptsp** [comment]
I encountered the [same issue](https://github.com/mr-bolle/docker-openvpn-pihole/issues/19#issue-606846960) as described below:
> Hello, big thank you for your work first!
> I've installed Docker and Docker-Compose on my Raspberry Pi 4 with Raspbian as OS following the instructions on [https://withblue.ink/2019/07/13/yes-you-can-run-docker-on-raspbian.html](url)
> Then I followed your instruction to get docker-openvpn-pihole installed. Everything worked fine until step 3. The following error message occured and the script was aborted:
> 
> _We are now at Step 3_
> _Easy-RSA error:_
> _The file '/etc/openvpn/vars' was not found._

I found [this answer](https://github.com/mr-bolle/docker-openvpn-pihole/issues/19#issuecomment-619565236) and executed it:
> git clone  https://github.com/mr-bolle/docker-openvpn-pihole.git -b rpi-dev && cd docker-openvpn-pihole && bash openvpn-install.sh

Once it ran, I encountered the same issue [as described here](https://github.com/mr-bolle/docker-openvpn-pihole/issues/19#issuecomment-636325757):
> Hello @mr-bolle,
> sorry for the late reply. I had some other issues with my Pi and no time to fix it...
> I've installed the provided image on a fresh set up Raspberry Pi 4, built up with the latest NextCloudPi-Image (03-28-20). Everything worked fine till "Generating a RSA private key". I've entered pass phrase and after that script ended with Easy-RSA Error.
> ## Generating a RSA private key
> .......+++++
> ...................................................+++++
> writing new private key to '/etc/openvpn/pki/private/nc.danielspi.de.key.XXXXeOpipA'
> 
> Using configuration from /usr/share/easy-rsa/openssl-easyrsa.cnf
> Enter pass phrase for /etc/openvpn/pki/private/ca.key:
> unable to load CA private key
> 3069400272:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:563:
> 3069400272:error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:p12_decr.c:108:
> 3069400272:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:p12_decr.c:139:
> 3069400272:error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib:pem_pkey.c:142:
> 
> Easy-RSA error:
> 
> signing failed (openssl output above may have more detail)

So I reran the script, and when it prompted for a pass phrase for /etc/openvpn/pki/private/ca.key, I entered a password.  The script then continued onwards, generating DH parameters on your Raspberry Pi 3.

**Comment by kahnwong** [comment]
the fix works for me 🙏
