### ISSUE TITLE
Can not access pihole admin page

### ISSUE THREAD

**Issue by k41c** [mr-bolle/docker-openvpn-pihole#20]
Hi mr-bolle,

First of all, great SW. Working finde out of the Box. 
But I can not call the pihole Web Page. 
What I try:
Choose the Browser of my choice.
Type in: http(s)://ipOfServer:portFromComposeFile
Try different ips:
Ip of external server with and without vpn connected
Ip of Internal pihole 172.110.1.4 
May you have a smal hint how to connect.

Thanks and Regards

EDIT If I disconnect VPN I'll able to connect. Seems somting with the Routing wont work. 
By the way. To protect the pihole web admin. World be great only allow connection over VPN.

**Comment by mr-bolle** [comment]
If you want to access the pi-hole admin page over your external IP/dynamic-dns your have to create a port forward to port 800 (_**not recommended**_) 

Please share your `docker-compose ps` and your IP address of your host `hostname -I`

You should use the local IP of your host, with the exposed port.

**Comment by k41c** [comment]
Many thanks, mr-bolle for the Fast response. 
I hat a deeper look inside docker network and found my sollten as following. 
1. Clear all Exposed ports for piHole in .yml
2. Get the network driver name through "docker network ls", in this case as found in the .yml file is "vpn-net".
3. Run "docker network inspect vpn-net" and looking for the ip of piHole, in this case 172.110.1.4 
4. Connect vpn
5. Enter ip found unter 3.
6. Voila get access to piHole admin Web page and only over the VPN :)
