### ISSUE TITLE
Use Pi-hole for LAN devices at home

### ISSUE THREAD

**Issue by NCGNConsulting** [mr-bolle/docker-openvpn-pihole#21]
Hello @mr-bolle,

First of all thank you for your job, I tested connecting to OpenVPN through cell and it's blocking ads.

I'm trying to use Docker Pi-hole as DNS to also block all ads when I navigate from home by LAN without connecting to OpenVPN.

I tried changing DNS on router by setting Pi IP, and also tied to set Dcoker network gateway IP and Pihole docker network IP.

I'm not a network expert, last time I used Pihole (without Docker), I added Pi IP as DNS in router. With Docker, not sure which IP do I need to setup.

It would be great to complete this functionality, blocking all ads also in my home network!.

Thank you again.

**Comment by mr-bolle** [comment]
Please check the official docker image https://github.com/pi-hole/docker-pi-hole

You have to set the local IP from your Raspberry Pi into your router as the customer DNS Server, then you have network wide blocking of advertising.

**Comment by mr-bolle** [comment]
Hi @NCGNConsulting

Now I have found a solution, you only must adjust the host port from `553` to `53` and remove the **#**

And if you restart with `docker compose restart` you should be able to block also local advertising. 

https://github.com/mr-bolle/docker-openvpn-pihole/blob/11b96d52646991738f8a8d6b80e37c9229c48918/docker-compose.yml#L48-L49

**Comment by NCGNConsulting** [comment]
Thank you @mr-bolle. That's perfect!

I will have a look as soon as I can.

Best Regards.
