### ISSUE TITLE
Pihole to be used from LAN (home) 

### ISSUE THREAD

**Issue by NCGNConsulting** [mr-bolle/docker-openvpn-pihole#22]
Hello @mr-bolle,

First of all thank you for your job, I tested connecting to OpenVPN through cell and it's blocking ads.

I'm trying to use Docker Pi-hole as DNS to also block all ads when I navigate from home by LAN without connecting to OpenVPN.

I tried changing DNS on router by setting Pi IP, and also tied to set Dcoker network gateway IP and Pihole docker network IP.

I'm not a network expert, last time I used Pihole (without Docker), I added Pi IP as DNS in router. With Docker, not sure which IP do I need to setup.

It would be great to complete this functionality, blocking all ads also in my home network!.

Thank you again.

**Comment by mr-bolle** [comment]
https://github.com/mr-bolle/docker-openvpn-pihole/issues/21#issuecomment-759448684
