### ISSUE TITLE
Dockerfile.aarch64 same file error

### ISSUE THREAD

**Issue by fisherd80** [mr-bolle/docker-openvpn-pihole#23]
Evening,

I have attempt to run the script as stated within this Github, but I repeatedly get this error:

`cp: 'Dockerfile.aarch64' and 'Dockerfile.aarch64' are the same file`

I am unsure what the cause of this, and would like some advice.  Any help would be appreciated.

**Comment by mr-bolle** [comment]
Hi please try again (delete the folder and git clone again)

https://github.com/mr-bolle/docker-openvpn-pihole/commit/11b96d52646991738f8a8d6b80e37c9229c48918

**Comment by fisherd80** [comment]
Thank you.
