### ISSUE TITLE
Error: "Device "tun0" does not exist."

### ISSUE THREAD

**Issue by Cyril-10** [mr-bolle/docker-openvpn-pihole#24]
### Context
I have **pihole set up already and running in a Docker Container** on a Apple silicon Mac.
Everything is **working well**.
But I want to make it **work with OpenVPN**(to allow iPhone to access even outdoor to block ADs), 
but **I didn't use "tun0"(but eth0)** at the very beginning and I don't know where to config it. 
Is there a way to change eth0 to tun0 **or add tun0** to make it work with OpenVPN?
Thank you very much😃

### more details:

Pihole running in a container. Config command to pihole I used:
docker run --name=pihole1 -e TZ=Taiwan -e jq-UbajZ=password -e SERVERIP=192.168.0.69 -v pihole_app:/etc/pihole -v dns_config:/etc/dnsmasq.d -p 81:80 -p 53:53/tcp -p 53:53/udp --restart=unless-stopped pihole/pihole

**pihole version**
  Pi-hole version is v5.11.4 (Latest: v5.11.4)
  AdminLTE version is v5.13 (Latest: v5.13)
  FTL version is v5.16.3 (Latest: v5.16.3)

**Comment by mr-bolle** [comment]
Pihole don't create a tun0 network, this openvpn create and use for the VPN connection.

If you want to use pihole local and pihole with openvpn separately, you have to change this dns port from example 53:53 to a other host port example 553:53

Your TZ environment variables are wrong. You should use Asia/Taipe

```
Is there a way to change eth0 to tun0 or add tun0 to make it work with OpenVPN?
```

The tun0 network you need only into the container, this image creates it by themselves.

**Comment by Cyril-10** [comment]
Thank you for your answers :)
